steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'cloud/Dockerfile', '-t', 'us-central1-docker.pkg.dev/svgslides-prod/svg-to-slides/svg-to-slides', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/svgslides-prod/svg-to-slides/svg-to-slides']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - run
      - deploy
      - svg-to-slides
      - --image=us-central1-docker.pkg.dev/svgslides-prod/svg-to-slides/svg-to-slides
      - --region=us-central1
      - --project=svgslides-prod
images:
  - 'us-central1-docker.pkg.dev/svgslides-prod/svg-to-slides/svg-to-slides'
options:
  logging: CLOUD_LOGGING_ONLY
